// async actions
export const GET_HISTORY = 'GET_HISTORY';
export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
export const GET_HISTORY_FAILURE = 'GET_HISTORY_FAILURE';

export const GET_HISTORY_BY_ID = 'GET_HISTORY_BY_ID';
export const GET_HISTORY_BY_ID_SUCCESS = 'GET_HISTORY_BY_ID_SUCCESS';
export const GET_HISTORY_BY_ID_FAILURE = 'GET_HISTORY_BY_ID_FAILURE';
